@startuml


'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false


class TopUpUI
class TopUpCntrl
class AccountCardRepo
class TransactionRepo
class AccountCard
class TopUp
abstract class Transaction


TopUpCntrl : insertCard(mecNum)
TopUpCntrl : topUpCard(amount, cashier)
AccountCardRepo : findByMecNum(mecNum)
TransactionRepo : save(topUp)
Transaction : notifyObservers()

Transaction <|-- TopUp : is a
TopUpUI .> TopUpCntrl
TopUpCntrl .> AccountCardRepo
TopUpCntrl .> TransactionRepo
TopUpCntrl .> TopUp
Transaction "*" o-> "1" AccountCard : references
AccountCardRepo "1" -- "*" AccountCard : retrieves


@enduml